build: false
clone_depth: 1
clone_folder: c:\projects\php-grf
image: Visual Studio 2015
configuration:
- php56
- php70
- php71
- php72
- php73

cache:
    - '%LOCALAPPDATA%\Composer\files'
    - c:\projects\php-grf\composer.phar

init:
    - SET PATH=c:\php;C:\Ruby22\bin;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)
    - REG ADD "HKEY_CURRENT_USER\Software\Microsoft\Command Processor" /v DelayedExpansion /t REG_DWORD /d 1 /f

install:
    - mkdir c:\memcached && cd c:\memcached
    - appveyor DownloadFile https://github.com/carloshenrq/chzapp/releases/download/v0.1.2/memcached-win32-1.4.4-14.zip
    - 7z x memcached-win32-1.4.4-14.zip -y >nul
    - memcached.exe -d install
    - memcached.exe -d start
    - cd \
    - appveyor DownloadFile https://github.com/carloshenrq/chzapp/releases/download/v0.1.2/%CONFIGURATION%.zip
    - 7z x %CONFIGURATION%.zip -y >nul
    - del /Q *.zip
    - cd c:\php
    - appveyor DownloadFile https://raw.githubusercontent.com/symfony/binary-utils/master/cacert.pem
    - echo extension=php_gettext.dll >> php.ini
    - echo curl.cainfo=c:\php\cacert.pem >> php.ini
    - cd c:\projects\php-grf
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - IF %APPVEYOR_REPO_BRANCH%==master (SET COMPOSER_ROOT_VERSION=dev-master) ELSE (SET COMPOSER_ROOT_VERSION=%APPVEYOR_REPO_BRANCH%.x-dev)
    - php composer.phar update --no-progress --ansi
    - SET COMPOSER_ROOT_VERSION=

before_test:
    - ruby -v
    - gem -v
    - bundle -v
    - php -v

test_script:
    - cd c:\projects\php-grf
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_test:
    - cd c:\projects\php-grf
    - appveyor DownloadFile https://codecov.io/bash -FileName codecov.sh
    - bash codecov.sh
    - vendor/bin/codacycoverage clover coverage.xml
